language: r
cache: packages
dist: xenial
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

r_packages:
  - rgdal
  - sf
  - devtools

sudo: required

script:
  - R CMD INSTALL ../geocompr/
  - make html

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
